[2023-03-06T23:05:28.054+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bitcoin_first_webscrape.get_transform_historical_data manual__2023-03-06T23:05:19.843605+00:00 [queued]>
[2023-03-06T23:05:28.104+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bitcoin_first_webscrape.get_transform_historical_data manual__2023-03-06T23:05:19.843605+00:00 [queued]>
[2023-03-06T23:05:28.114+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-06T23:05:28.120+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-06T23:05:28.126+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-06T23:05:28.197+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): get_transform_historical_data> on 2023-03-06 23:05:19.843605+00:00
[2023-03-06T23:05:28.238+0000] {standard_task_runner.py:55} INFO - Started process 448 to run task
[2023-03-06T23:05:28.264+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_first_webscrape', 'get_transform_historical_data', 'manual__2023-03-06T23:05:19.843605+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpvsrqk0yb']
[2023-03-06T23:05:28.275+0000] {standard_task_runner.py:83} INFO - Job 108: Subtask get_transform_historical_data
[2023-03-06T23:05:29.019+0000] {task_command.py:388} INFO - Running <TaskInstance: bitcoin_first_webscrape.get_transform_historical_data manual__2023-03-06T23:05:19.843605+00:00 [running]> on host 12a6d3b9daec
[2023-03-06T23:05:29.307+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bitcoin_first_webscrape
AIRFLOW_CTX_TASK_ID=get_transform_historical_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-06T23:05:19.843605+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-06T23:05:19.843605+00:00
[2023-03-06T23:05:29.326+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/history.py", line 48, in hist_transf
    old_price_df = pd.read_csv(os.path.join(data_dir,config['kaggle_data']), header=0)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '../data/BTC_4_13_2021.csv'
[2023-03-06T23:05:29.372+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=bitcoin_first_webscrape, task_id=get_transform_historical_data, execution_date=20230306T230519, start_date=20230306T230528, end_date=20230306T230529
[2023-03-06T23:05:29.415+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 108 for task get_transform_historical_data ([Errno 2] No such file or directory: '../data/BTC_4_13_2021.csv'; 448)
[2023-03-06T23:05:29.495+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-06T23:05:29.642+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
