[2023-03-06T22:44:54.436+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bitcoin_first_webscrape.get_transform_historical_data scheduled__2023-03-05T06:30:00+00:00 [queued]>
[2023-03-06T22:44:54.513+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: bitcoin_first_webscrape.get_transform_historical_data scheduled__2023-03-05T06:30:00+00:00 [queued]>
[2023-03-06T22:44:54.515+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-06T22:44:54.517+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-06T22:44:54.519+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-06T22:44:54.677+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): get_transform_historical_data> on 2023-03-05 06:30:00+00:00
[2023-03-06T22:44:54.753+0000] {standard_task_runner.py:55} INFO - Started process 1224 to run task
[2023-03-06T22:44:54.813+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_first_webscrape', 'get_transform_historical_data', 'scheduled__2023-03-05T06:30:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmphxt27g8c']
[2023-03-06T22:44:54.821+0000] {standard_task_runner.py:83} INFO - Job 98: Subtask get_transform_historical_data
[2023-03-06T22:44:55.377+0000] {task_command.py:388} INFO - Running <TaskInstance: bitcoin_first_webscrape.get_transform_historical_data scheduled__2023-03-05T06:30:00+00:00 [running]> on host a1cb7a35fb39
[2023-03-06T22:44:55.729+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bitcoin_first_webscrape
AIRFLOW_CTX_TASK_ID=get_transform_historical_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-05T06:30:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-05T06:30:00+00:00
[2023-03-06T22:44:55.763+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/history.py", line 41, in hist_transf
    old_price_df = pd.read_csv('./data/BTC_4_13_2021.csv', header=0)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: './data/BTC_4_13_2021.csv'
[2023-03-06T22:44:55.806+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=bitcoin_first_webscrape, task_id=get_transform_historical_data, execution_date=20230305T063000, start_date=20230306T224454, end_date=20230306T224455
[2023-03-06T22:44:55.863+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 98 for task get_transform_historical_data ([Errno 2] No such file or directory: './data/BTC_4_13_2021.csv'; 1224)
[2023-03-06T22:44:55.925+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-06T22:44:56.003+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
